# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人姓名')),
                ('recv_phone', models.CharField(max_length=255, verbose_name='收货人联系方式')),
                ('provice', models.CharField(max_length=255, verbose_name='省份')),
                ('city', models.CharField(max_length=255, verbose_name='市区')),
                ('country', models.CharField(max_length=255, verbose_name='县区')),
                ('street', models.CharField(max_length=255, verbose_name='街道')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='详细描述')),
                ('status', models.CharField(max_length=255, verbose_name='默认地址')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.CharField(max_length=255, verbose_name='商品单价')),
                ('stock', models.CharField(max_length=255, verbose_name='商品库存')),
                ('count', models.CharField(max_length=255, verbose_name='销售数量')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/goods/', verbose_name='商品图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品描述')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('path', models.ImageField(blank=True, null=True, upload_to='static/img/goods/', verbose_name='商品图片')),
                ('status', models.CharField(max_length=255)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='所属商品')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('gt_name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='static/img/goods/', verbose_name='图片')),
                ('gt_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型描述')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人')),
                ('recv_address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('recv_phone', models.CharField(max_length=255, verbose_name='联系方式')),
                ('recv_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('totale', models.CharField(max_length=255, verbose_name='总计金额')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('oi_goods_id', models.CharField(max_length=255, verbose_name='订单编号')),
                ('oi_goods_name', models.CharField(max_length=255, verbose_name='订单商品名称')),
                ('oi_goods_price', models.CharField(max_length=255, verbose_name='订单商品金额')),
                ('oi_goods_count', models.CharField(max_length=255, verbose_name='订单商品数量')),
                ('deal_price', models.CharField(max_length=255, verbose_name='成交价格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Order', verbose_name='所属订单')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.CharField(max_length=255, verbose_name='数量数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
                ('subtotal', models.CharField(max_length=255, verbose_name='总计金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='购物车商品')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=225, verbose_name='店铺名称')),
                ('cover', models.ImageField(default='static/img/shops/1.jpg', upload_to='static/img/shops/', verbose_name='店铺封面')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺描述')),
                ('opener_time', models.DateTimeField(auto_now_add=True, verbose_name='开店时间')),
                ('status', models.CharField(max_length=255, verbose_name='店铺状态')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=255, verbose_name='用户姓名')),
                ('userpass', models.CharField(max_length=255, verbose_name='用户密码')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('age', models.CharField(max_length=255, verbose_name='用户年龄')),
                ('gender', models.CharField(max_length=255, verbose_name='用户性别')),
                ('header', models.ImageField(blank=True, null=True, upload_to='static/img/users/', verbose_name='用户头像')),
                ('phone', models.CharField(max_length=12, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='电子邮箱')),
                ('regist_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, verbose_name='上次登录时间')),
                ('status', models.CharField(max_length=255, verbose_name='用户状态')),
            ],
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='所属类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Store', verbose_name='所属店铺'),
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.User', verbose_name='所属用户'),
        ),
    ]
